<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IPHON 11</title>
    
    <link rel="icon"  href="http://localhost/SitioWeb/imagenes/tienda.jpg">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <style type="text/css">
    
    body {
      
       background-image: url(https://www.solofondos.com/wp-content/uploads/2016/01/fondo-blanco-y-negro.jpg);
       
       font-family:'Permanent Marker', cursive;
      
}

  
   small{

    background-color: black;
   }
   header{

     background-color: black;
   }
   h1{ 
     
     
  color:  darkturquoise; }

  center{ 
     
     
     color:  black; }
 

.imagen1{
          width:1700px;
          height:650px;
          } 
.imagen2{
          width:1700px;
          height:650px;
          } 
.imagen3{
          width:1700px;
          height:650px;
          } 
 
.imagenes{
          width:450px;
          height:420px;
          } 
.imagenes1{
          width:700x;
          height:420px;
          } 

</style>  

<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="http://localhost/SitioWeb/index.php/tienda1"><h1 style="color:greenyellow">TIENDA VIRTUAL FET</h1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <b<a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><h4 style="color:aliceblue">CONTACTOS</h4></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="#"><h4 style="color:aliceblue">MI CARRITO</h4></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
     
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><h4 style="color:aliceblue" >PRODUCTOS</h4></a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="http://localhost/SitioWeb/index.php/tienda1/tecno"><h3>TECNOLOGIA</h3></a>
          <a class="dropdown-item" href="http://localhost/SitioWeb/index.php/tienda1/compus"><h3>COMPUTADORES</h3></a>
          <a class="dropdown-item" href="http://localhost/SitioWeb/index.php/tienda1/celulares"><h3>SMARFONS</h3></a>
          <a class="dropdown-item" href="http://localhost/SitioWeb/index.php/tienda1/moda#"><h3>MODA</h3></a>
         
          <a class="dropdown-item" href="http://localhost/SitioWeb/index.php/tienda1/productosdelhogar"><h3>PRODUCTOS DEL HOGAR</h3></a>
          <a class="dropdown-item" href="http://localhost/SitioWeb/index.php/tienda1/electrodomesticos"><h3>ELECTRODOMESTICOS</h3></a>
        </div>
      </li>
    </ul>
  
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">BUSCAR</button>
    </form>
  </div>
        </nav
        
      </div>
    </div>
  </header>

  <br><div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
    </nav>
    </div></br>
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="imagen1" src="https://eloutput.com/app/uploads-eloutput.com/2019/09/apple-iphone-11-analisis-6.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="imagen2" src="https://img-cdn.hipertextual.com/files/2019/09/hipertextual-iphone-11-pro-2019416093.jpg?strip=all&lossy=1&quality=70&ssl=1" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="imagen3" src="https://ocdn.eu/images/pulscms/NTk7MDA_/8acba302-7938-4184-a7da-ec03a6da775d.png" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<center><h1 class="news"><small>IPHON 11</small></h1></center>
<br></br>
<center><h1 class="news"><small>Características principales</small></h1></center>
<br></br>
		<div class="row">

		    <div class="col-md-6 col-xs-12">
			<ul class="fa-ul">
			    <li><span data-toggle="tooltip" title="Pantalla y resolución"><i class="fa-li fa fa-mobile fa-lg"></i>  <strong><h2>Pantalla: 6.2", 828 x 1792 pixels</h2></strong></span></li>		      <li><span data-toggle="tooltip" title="Procesador"><i class="fa-li fa fa-tachometer"></i>  <strong><h2>Procesador: apple A13 bionic</h2></strong></span></li>		      <li><span data-toggle="tooltip" title="Memoria RAM"><i class="fa-li fa fa-cogs"></i>  <strong><h2>RAM: 8GB/12GB</h2></strong></span></li>
				  <li><span data-toggle="tooltip" title="Almacenamiento"><i class="fa-li fa fa-microchip"></i>  <strong><h2>Almacenamiento: 64gb/128GB</h2></strong></span></li>				  <li><span data-toggle="tooltip" title="Expansión de memoria"><i class="fa-li fa fa-archive"></i>  <strong><h2>Expansión: microSD</h2></strong></span></li>			
			</ul>
		    </div>
		    <div class="col-md-6 col-xs-12">
					<ul class="fa-ul">
					<li><span data-toggle="tooltip" title="Cámara"><i class="fa-li fa fa-camera"></i>  <strong><h2>Cámara: dual 12mp+12 mp</h2></strong></span></li>					<li><span data-toggle="tooltip" title="Batería"><i class="fa-li fa fa-battery"></i>  <strong><h2>Batería: 3600 mAh</h2></strong></span></li>					<li><span data-toggle="tooltip" title="Sistema operativo"><i class="fa-li fa fa-code"></i>  <strong><h2 IOS 13 ></h2></strong></span></li>				  <li><span data-toggle="tooltip" title="Perfil"><i class="fa-li fa fa-expand"></i>  <strong><h2> 8.3 mm</h2></strong></span></li>				  <li><span data-toggle="tooltip" title="Peso"><i class="fa-li fa fa-balance-scale"></i>  <strong><h2>Peso: 194 g</h2></strong></span></li>					<li><span data-toggle="tooltip" title="Precio"><i class="fa-li fa fa-usd"></i>  <strong></strong></span></li>					</ul>
		     <div class="clear"></div>
		    </div>

        </div>
        <center><h1 class="news"><small>precio: $3.600.000</small></h1></center>
<center><a href="#" class="btn btn-secondary btn-lg" role="button" aria-pressed="true">Lo quiero</a></center>



    <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-4 mb-4 font-italic border-bottom">
        From the Firehose
      </h3>
<center>
      <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">

          <li><a href="https://www.facebook.com/"><H2>Facebook</H2></a></li>
          
        </ol>
      </div>
</center>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->

 </main><!-- /.container -->

 <footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/"></a> by <a href="https://twitter.com/mdo"></a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>
</body>

</html>